apiVersion: v1
kind: Service
metadata:
  name: echo-server
spec:
  type: NodePort
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: 5678          # Port on the Service
      targetPort: 5678    # Port on the Pod
      nodePort: 30000     # Specific NodePort