---
- name: My web server play
  hosts: tag_Role_webserver
  gather_facts: no
  remote_user: ubuntu
  become: yes

  tasks:
  - name: Wait for connection
    ansible.builtin.wait_for_connection:
      timeout: 60

  - name: Gather facts
    ansible.builtin.gather_facts:

  - name: ensure apache is at the latest version
    ansible.builtin.package:
      name:
        - apache2
      state: latest
  
  - name: ensure apache service is started
    ansible.builtin.service:
      name: apache2
      state: started

  - name: Create index.html in /var/www/html/
    template: 
      src: index.html.j2 
      dest: /var/www/html/index.html
    vars:
      message: "Hello from EC2 instnace built with terraform and converged with Ansible. My host name is {{ inventory_hostname }}"