apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  containers:
  - name: my-app-container
    image: my-app:latest
    imagePullPolicy: Never
    ports:
      - containerPort: 8000
    
    env:
      - name: DATABASE_HOST
        valueFrom:
          configMapKeyRef:
            name: my-app-config-env
            key: DATABASE_HOST
      - name: DATABASE_NAME
        valueFrom:
          configMapKeyRef:
            name: my-app-config-env
            key: DATABASE_NAME
    
    volumeMounts:
      - name: config-file-volume
        mountPath: /app/config.yaml
        subPath: config

  volumes:
  - name: config-file-volume
    configMap:
      name: my-app-config-file