apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
  labels:
    app: my-app
spec:
  containers:
    - name: my-app-container
      image: my-app:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8000
      resources:
        # Define the minimum required resourses to schedule the pod
        requests:
          memory: "128Mi"
          cpu: "250m"
        # Define the maximus resources that the pod can consume
        limits:
          memory: "256Mi"
          cpu: "500m"
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 5
      startupProbe:
        httpGet:
          path: /health
          port: 8000
        failureThreshold: 30
        periodSeconds: 10