apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  containers:
  - name: my-app-container
    image: my-app:latest
    imagePullPolicy: Never
    ports:
      - containerPort: 8000
    
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: my-app-secrets
            key: username

      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-app-secrets
            key: password